# Generated by Django 3.2.4 on 2021-11-08 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catImage/', verbose_name='*Image')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Tovar nomi')),
                ('price', models.CharField(max_length=150, verbose_name='Narxi')),
                ('img4', models.ImageField(upload_to='product_img/', verbose_name='Rasmi 4')),
                ('img1', models.ImageField(upload_to='product_img/', verbose_name='Rasmi 1')),
                ('img2', models.ImageField(upload_to='product_img/', verbose_name='Rasmi 2')),
                ('img3', models.ImageField(upload_to='product_img/', verbose_name='Rasmi 3')),
                ('val', models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD'), ('rub', 'RUB')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.category')),
                ('like', models.ManyToManyField(related_name='liked_products', to=settings.AUTH_USER_MODEL)),
                ('seen', models.ManyToManyField(related_name='seen_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=350, verbose_name='*Title')),
                ('subtitle', models.CharField(max_length=350, verbose_name='*Subtitle')),
                ('slug', models.SlugField(verbose_name='*')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.category')),
            ],
            options={
                'verbose_name': 'category Translation',
                'db_table': 'main_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
